---

- Developer:
    - DuckDuckGo:
        - abbr: AI
          href: https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
    - Github:
        - abbr: GH
          href: https://github.com/stalbrec
    - git-TI:
        - abbr: TI
          href: https://git-dmz.thuenen.de

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
