---

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
- search:
    provider: duckduckgo
    target: _parent
    showSearchSuggestions: true
